name: GuildForge
version: 1.0.0
main: ru.guildforge.GuildForge
api-version: 1.21
folia-supported: true

softdepend:
  - PlaceholderAPI

commands:
  guild:
    description: "Открыть меню гильдий"
    usage: "/guild"
    aliases: [g, гильдия]
  guildadmin:
    description: "Админские команды GuildForge"
    usage: "/guildadmin <reload/info/setguild/addcontribution>"
    permission: guildforge.admin
    aliases: [ga, админгильдия]
  warp:
    description: "Управление варпами (только для картографов)"
    usage: "/warp <create/delete/list> [название]"
    aliases: [варп]

permissions:
  guildforge.use:
    description: "Разрешает использовать /guild"
    default: true
  guildforge.warp:
    description: "Разрешает использовать /warp (проверяется гильдия)"
    default: true
  guildforge.admin:
    description: "Админские команды"
    default: op
    children:
      guildforge.use: true
      guildforge.warp: true